spring:
  data:
    mongodb:
      host: 119.23.231.196
      port: 27017
      database: recommend 
      replica-set: mgset-3590061
      # 客户端的连接数
      connections-per-host: 20
      # 客户端最小连接数
      min-connections-per-host: 20